# QIF Analyses (AOL experimental - Google Topics v1 Classification)

In [1]:
import numpy, pandas, qif
from collections import Counter
from bvmlib.bvm import BVM

## AOL experimental dataset with Google Topics Classification v1

In [2]:
%%time
# Loads AOL-experimental-Google-Topics-Classification-v1 dataset into aol_experimental_google_browsing_history DataFrame.
aol_experimental_google_browsing_history = pandas.read_csv('AOL-experimental-Google-Topics-Classification-v1.csv', low_memory=False, on_bad_lines='warn', index_col=0)

CPU times: user 1.53 s, sys: 567 ms, total: 2.1 s
Wall time: 1.6 s

In [3]:
display(aol_experimental_google_browsing_history)

,RandID,BrowsingHistory,AllTopics,sTopics
0,1,"[('kidshealth.org', Timestamp('2006-03-01 11:5...","[""'258'"", ""'276'"", ""'258'"", ""'276'"", ""'258'"", ...","[""'149'"", ""'234'"", ""'258'"", ""'276'"", ""'56'""]"
1,3,"[('google.com', Timestamp('2006-03-18 15:06:00...","[""'219'"", ""'239'"", ""'289'"", ""'258'"", ""'276'"", ...","[""'1'"", ""'180'"", ""'186'"", ""'258'"", ""'276'""]"
2,4,"[('foxnews.com', Timestamp('2006-03-12 20:33:2...","[""'1'"", ""'243'"", ""'219'""]","[""'1'"", ""'217'"", ""'219'"", ""'243'"", ""'306'""]"
3,5,"[('foxnews.com', Timestamp('2006-03-22 00:22:5...","[""'1'"", ""'243'"", ""'103'"", ""'1'"", ""'215'"", ""'24...","[""'1'"", ""'103'"", ""'215'"", ""'239'"", ""'243'""]"
4,6,"[('google.com', Timestamp('2006-03-06 15:07:17...","[""'219'"", ""'219'"", ""'219'"", ""'219'"", ""'219'"", ...","[""'12'"", ""'219'"", ""'289'"", ""'299'"", ""'314'""]"
...,...,...,...,...
198018,521683,"[('imdb.com', Timestamp('2006-04-08 17:05:00')...","[""'12'"", ""'45'"", ""'1'"", ""'243'""]","[""'1'"", ""'12'"", ""'230'"", ""'243'"", ""'45'""]"
198019,521686,"[('flickr.com', Timestamp('2006-03-12 21:19:11...","[""'42'"", ""'250'"", ""'253'"", ""'57'"", ""'62'"", ""'8...","[""'248'"", ""'250'"", ""'253'"", ""'62'"", ""'83'""]"
198020,521688,"[('aol.com', Timestamp('2006-03-16 16:59:47'))...","[""'1'"", ""'215'"", ""'243'"", ""'289'"", ""'275'""]","[""'1'"", ""'215'"", ""'243'"", ""'275'"", ""'289'""]"
198021,521689,"[('msn.com', Timestamp('2006-03-04 01:07:45'))...","[""'1'"", ""'215'"", ""'243'"", ""'219'"", ""'219'"", ""'...","[""'1'"", ""'215'"", ""'219'"", ""'243'"", ""'334'""]"
198022,521691,"[('ups.com', Timestamp('2006-03-07 21:29:17'))...","[""'103'"", ""'103'"", ""'103'"", ""'219'"", ""'219'""]","[""'103'"", ""'215'"", ""'219'"", ""'336'"", ""'81'""]"

## Experiment 6: Third-party cookies on AOL experimental dataset with Google Taxonomy Classification v1

### Privacy

In [4]:
temp = aol_experimental_google_browsing_history.copy()
temp['UID'] = temp['RandID']
temp = temp.drop(columns=['BrowsingHistory'], inplace=False)
display(temp, temp.nunique())

,RandID,AllTopics,sTopics,UID
0,1,"[""'258'"", ""'276'"", ""'258'"", ""'276'"", ""'258'"", ...","[""'149'"", ""'234'"", ""'258'"", ""'276'"", ""'56'""]",1
1,3,"[""'219'"", ""'239'"", ""'289'"", ""'258'"", ""'276'"", ...","[""'1'"", ""'180'"", ""'186'"", ""'258'"", ""'276'""]",3
2,4,"[""'1'"", ""'243'"", ""'219'""]","[""'1'"", ""'217'"", ""'219'"", ""'243'"", ""'306'""]",4
3,5,"[""'1'"", ""'243'"", ""'103'"", ""'1'"", ""'215'"", ""'24...","[""'1'"", ""'103'"", ""'215'"", ""'239'"", ""'243'""]",5
4,6,"[""'219'"", ""'219'"", ""'219'"", ""'219'"", ""'219'"", ...","[""'12'"", ""'219'"", ""'289'"", ""'299'"", ""'314'""]",6
...,...,...,...,...
198018,521683,"[""'12'"", ""'45'"", ""'1'"", ""'243'""]","[""'1'"", ""'12'"", ""'230'"", ""'243'"", ""'45'""]",521683
198019,521686,"[""'42'"", ""'250'"", ""'253'"", ""'57'"", ""'62'"", ""'8...","[""'248'"", ""'250'"", ""'253'"", ""'62'"", ""'83'""]",521686
198020,521688,"[""'1'"", ""'215'"", ""'243'"", ""'289'"", ""'275'""]","[""'1'"", ""'215'"", ""'243'"", ""'275'"", ""'289'""]",521688
198021,521689,"[""'1'"", ""'215'"", ""'243'"", ""'219'"", ""'219'"", ""'...","[""'1'"", ""'215'"", ""'219'"", ""'243'"", ""'334'""]",521689
198022,521691,"[""'103'"", ""'103'"", ""'103'"", ""'219'"", ""'219'""]","[""'103'"", ""'215'"", ""'219'"", ""'336'"", ""'81'""]",521691

RandID       198023
AllTopics    148089
sTopics      110870
UID          198023
dtype: int64

In [5]:
%%time
E6P = BVM(temp)
E6P.qids(['UID'])
E6P.sensitive(['RandID'])
results = E6P.assess()

CPU times: user 1.72 s, sys: 0 ns, total: 1.72 s
Wall time: 1.72 s

In [6]:
display(results['re_id'], results['att_inf'])

,QID,dCR,pCR,Prior,Posterior,Histogram
0,['UID'],1.0,198023,0.000005,1.0,"{'0': 0.0, '1': 0.0, '2': 0.0, '3': 0.0, '4': ..."

,QID,Sensitive,dCA,pCA,Prior,Posterior,Histogram
0,['UID'],RandID,0.0,198023.0,0.000005,1.0,"{'0': 0.0, '1': 0.0, '2': 0.0, '3': 0.0, '4': ..."

In [7]:
# Prior Bayes vulnerability.
display(results['re_id']['Prior'][0], results['att_inf']['Prior'][0])

5.0499184438171325e-06

5.0499184438171325e-06

In [8]:
# Posterior Bayes vulnerability.
display(results['re_id']['Posterior'][0], results['att_inf']['Posterior'][0])

1.0

1.0

In [9]:
# Bayes leakage.
display(results['re_id']['Posterior'][0]/results['re_id']['Prior'][0], results['att_inf']['Posterior'][0]/results['att_inf']['Prior'][0])

198023.0

198023.0

### Utility

In [10]:
temp = aol_experimental_google_browsing_history.copy()
temp = temp.rename(columns={'RandID':'UID'}, inplace=False)
display(temp, temp.nunique())

,UID,BrowsingHistory,AllTopics,sTopics
0,1,"[('kidshealth.org', Timestamp('2006-03-01 11:5...","[""'258'"", ""'276'"", ""'258'"", ""'276'"", ""'258'"", ...","[""'149'"", ""'234'"", ""'258'"", ""'276'"", ""'56'""]"
1,3,"[('google.com', Timestamp('2006-03-18 15:06:00...","[""'219'"", ""'239'"", ""'289'"", ""'258'"", ""'276'"", ...","[""'1'"", ""'180'"", ""'186'"", ""'258'"", ""'276'""]"
2,4,"[('foxnews.com', Timestamp('2006-03-12 20:33:2...","[""'1'"", ""'243'"", ""'219'""]","[""'1'"", ""'217'"", ""'219'"", ""'243'"", ""'306'""]"
3,5,"[('foxnews.com', Timestamp('2006-03-22 00:22:5...","[""'1'"", ""'243'"", ""'103'"", ""'1'"", ""'215'"", ""'24...","[""'1'"", ""'103'"", ""'215'"", ""'239'"", ""'243'""]"
4,6,"[('google.com', Timestamp('2006-03-06 15:07:17...","[""'219'"", ""'219'"", ""'219'"", ""'219'"", ""'219'"", ...","[""'12'"", ""'219'"", ""'289'"", ""'299'"", ""'314'""]"
...,...,...,...,...
198018,521683,"[('imdb.com', Timestamp('2006-04-08 17:05:00')...","[""'12'"", ""'45'"", ""'1'"", ""'243'""]","[""'1'"", ""'12'"", ""'230'"", ""'243'"", ""'45'""]"
198019,521686,"[('flickr.com', Timestamp('2006-03-12 21:19:11...","[""'42'"", ""'250'"", ""'253'"", ""'57'"", ""'62'"", ""'8...","[""'248'"", ""'250'"", ""'253'"", ""'62'"", ""'83'""]"
198020,521688,"[('aol.com', Timestamp('2006-03-16 16:59:47'))...","[""'1'"", ""'215'"", ""'243'"", ""'289'"", ""'275'""]","[""'1'"", ""'215'"", ""'243'"", ""'275'"", ""'289'""]"
198021,521689,"[('msn.com', Timestamp('2006-03-04 01:07:45'))...","[""'1'"", ""'215'"", ""'243'"", ""'219'"", ""'219'"", ""'...","[""'1'"", ""'215'"", ""'219'"", ""'243'"", ""'334'""]"
198022,521691,"[('ups.com', Timestamp('2006-03-07 21:29:17'))...","[""'103'"", ""'103'"", ""'103'"", ""'219'"", ""'219'""]","[""'103'"", ""'215'"", ""'219'"", ""'336'"", ""'81'""]"

UID                198023
BrowsingHistory    198023
AllTopics          148089
sTopics            110870
dtype: int64

In [11]:
%%time
E6U = BVM(temp)
E6U.qids(['UID'])
E6U.sensitive(['BrowsingHistory'])
results = E6U.assess()

CPU times: user 2.56 s, sys: 0 ns, total: 2.56 s
Wall time: 2.56 s

In [12]:
display(results['re_id'], results['att_inf'])

,QID,dCR,pCR,Prior,Posterior,Histogram
0,['UID'],1.0,198023,0.000005,1.0,"{'0': 0.0, '1': 0.0, '2': 0.0, '3': 0.0, '4': ..."

,QID,Sensitive,dCA,pCA,Prior,Posterior,Histogram
0,['UID'],BrowsingHistory,0.0,198023.0,0.000005,1.0,"{'0': 0.0, '1': 0.0, '2': 0.0, '3': 0.0, '4': ..."

In [13]:
# Prior Bayes vulnerability.
display(results['re_id']['Prior'][0], results['att_inf']['Prior'][0])

5.0499184438171325e-06

5.0499184438171325e-06

In [14]:
# Posterior Bayes vulnerability.
display(results['re_id']['Posterior'][0], results['att_inf']['Posterior'][0])

1.0

1.0

In [15]:
# Bayes leakage.
display(results['re_id']['Posterior'][0]/results['re_id']['Prior'][0], results['att_inf']['Posterior'][0]/results['att_inf']['Prior'][0])

198023.0

198023.0

## Experiment 7: Topics with Generalization on AOL experimental dataset with Google Taxonomy Classification v1

In [16]:
aol_experimental_google_generalization = aol_experimental_google_browsing_history

In [17]:
display(aol_experimental_google_generalization)

,RandID,BrowsingHistory,AllTopics,sTopics
0,1,"[('kidshealth.org', Timestamp('2006-03-01 11:5...","[""'258'"", ""'276'"", ""'258'"", ""'276'"", ""'258'"", ...","[""'149'"", ""'234'"", ""'258'"", ""'276'"", ""'56'""]"
1,3,"[('google.com', Timestamp('2006-03-18 15:06:00...","[""'219'"", ""'239'"", ""'289'"", ""'258'"", ""'276'"", ...","[""'1'"", ""'180'"", ""'186'"", ""'258'"", ""'276'""]"
2,4,"[('foxnews.com', Timestamp('2006-03-12 20:33:2...","[""'1'"", ""'243'"", ""'219'""]","[""'1'"", ""'217'"", ""'219'"", ""'243'"", ""'306'""]"
3,5,"[('foxnews.com', Timestamp('2006-03-22 00:22:5...","[""'1'"", ""'243'"", ""'103'"", ""'1'"", ""'215'"", ""'24...","[""'1'"", ""'103'"", ""'215'"", ""'239'"", ""'243'""]"
4,6,"[('google.com', Timestamp('2006-03-06 15:07:17...","[""'219'"", ""'219'"", ""'219'"", ""'219'"", ""'219'"", ...","[""'12'"", ""'219'"", ""'289'"", ""'299'"", ""'314'""]"
...,...,...,...,...
198018,521683,"[('imdb.com', Timestamp('2006-04-08 17:05:00')...","[""'12'"", ""'45'"", ""'1'"", ""'243'""]","[""'1'"", ""'12'"", ""'230'"", ""'243'"", ""'45'""]"
198019,521686,"[('flickr.com', Timestamp('2006-03-12 21:19:11...","[""'42'"", ""'250'"", ""'253'"", ""'57'"", ""'62'"", ""'8...","[""'248'"", ""'250'"", ""'253'"", ""'62'"", ""'83'""]"
198020,521688,"[('aol.com', Timestamp('2006-03-16 16:59:47'))...","[""'1'"", ""'215'"", ""'243'"", ""'289'"", ""'275'""]","[""'1'"", ""'215'"", ""'243'"", ""'275'"", ""'289'""]"
198021,521689,"[('msn.com', Timestamp('2006-03-04 01:07:45'))...","[""'1'"", ""'215'"", ""'243'"", ""'219'"", ""'219'"", ""'...","[""'1'"", ""'215'"", ""'219'"", ""'243'"", ""'334'""]"
198022,521691,"[('ups.com', Timestamp('2006-03-07 21:29:17'))...","[""'103'"", ""'103'"", ""'103'"", ""'219'"", ""'219'""]","[""'103'"", ""'215'"", ""'219'"", ""'336'"", ""'81'""]"

### Privacy

In [18]:
temp = aol_experimental_google_generalization.copy()
temp = temp.drop(columns=['BrowsingHistory','AllTopics'], inplace=False)
display(temp)

        RandID                                       sTopics
0            1  ["'149'", "'234'", "'258'", "'276'", "'56'"]
1            3   ["'1'", "'180'", "'186'", "'258'", "'276'"]
2            4   ["'1'", "'217'", "'219'", "'243'", "'306'"]
3            5   ["'1'", "'103'", "'215'", "'239'", "'243'"]
4            6  ["'12'", "'219'", "'289'", "'299'", "'314'"]
...        ...                                           ...
198018  521683     ["'1'", "'12'", "'230'", "'243'", "'45'"]
198019  521686   ["'248'", "'250'", "'253'", "'62'", "'83'"]
198020  521688   ["'1'", "'215'", "'243'", "'275'", "'289'"]
198021  521689   ["'1'", "'215'", "'219'", "'243'", "'334'"]
198022  521691  ["'103'", "'215'", "'219'", "'336'", "'81'"]

[198023 rows x 2 columns]

In [19]:
%%time
E7P = BVM(temp)
E7P.qids(['sTopics'])
E7P.sensitive(['RandID'])
results = E7P.assess()

CPU times: user 1.55 s, sys: 6.9 ms, total: 1.56 s
Wall time: 1.56 s

In [20]:
display(results['re_id'], results['att_inf'])

,QID,dCR,pCR,Prior,Posterior,Histogram
0,['sTopics'],0.487272,110870,0.000005,0.559884,"{'0': 0.09336289218929114, '1': 0.067365912040..."

,QID,Sensitive,dCA,pCA,Prior,Posterior,Histogram
0,['sTopics'],RandID,0.487272,110870.0,0.000005,0.559884,"{'0': 0.09336289218929114, '1': 0.067365912040..."

In [21]:
# Prior Bayes vulnerability.
display(results['re_id']['Prior'][0], results['att_inf']['Prior'][0])

5.0499184438171325e-06

5.0499184438171325e-06

In [22]:
# Posterior Bayes vulnerability.
display(results['re_id']['Posterior'][0], results['att_inf']['Posterior'][0])

0.5598844578660055

0.5598844578660055

In [23]:
# Bayes leakage.
display(results['re_id']['Posterior'][0]/results['re_id']['Prior'][0], results['att_inf']['Posterior'][0]/results['att_inf']['Prior'][0])

110870.0

110870.0

### Utility

In [24]:
temp = aol_experimental_google_generalization.copy()
temp = temp.drop(columns=['RandID','AllTopics'], inplace=False)
display(temp)

,BrowsingHistory,sTopics
0,"[('kidshealth.org', Timestamp('2006-03-01 11:5...","[""'149'"", ""'234'"", ""'258'"", ""'276'"", ""'56'""]"
1,"[('google.com', Timestamp('2006-03-18 15:06:00...","[""'1'"", ""'180'"", ""'186'"", ""'258'"", ""'276'""]"
2,"[('foxnews.com', Timestamp('2006-03-12 20:33:2...","[""'1'"", ""'217'"", ""'219'"", ""'243'"", ""'306'""]"
3,"[('foxnews.com', Timestamp('2006-03-22 00:22:5...","[""'1'"", ""'103'"", ""'215'"", ""'239'"", ""'243'""]"
4,"[('google.com', Timestamp('2006-03-06 15:07:17...","[""'12'"", ""'219'"", ""'289'"", ""'299'"", ""'314'""]"
...,...,...
198018,"[('imdb.com', Timestamp('2006-04-08 17:05:00')...","[""'1'"", ""'12'"", ""'230'"", ""'243'"", ""'45'""]"
198019,"[('flickr.com', Timestamp('2006-03-12 21:19:11...","[""'248'"", ""'250'"", ""'253'"", ""'62'"", ""'83'""]"
198020,"[('aol.com', Timestamp('2006-03-16 16:59:47'))...","[""'1'"", ""'215'"", ""'243'"", ""'275'"", ""'289'""]"
198021,"[('msn.com', Timestamp('2006-03-04 01:07:45'))...","[""'1'"", ""'215'"", ""'219'"", ""'243'"", ""'334'""]"
198022,"[('ups.com', Timestamp('2006-03-07 21:29:17'))...","[""'103'"", ""'215'"", ""'219'"", ""'336'"", ""'81'""]"

In [25]:
%%time
E7U = BVM(temp)
E7U.qids(['sTopics'])
E7U.sensitive(['BrowsingHistory'])
results = E7U.assess()

CPU times: user 2.72 s, sys: 7.5 ms, total: 2.72 s
Wall time: 2.72 s

In [26]:
display(results['re_id'], results['att_inf'])

,QID,dCR,pCR,Prior,Posterior,Histogram
0,['sTopics'],0.487272,110870,0.000005,0.559884,"{'0': 0.09336289218929114, '1': 0.067365912040..."

,QID,Sensitive,dCA,pCA,Prior,Posterior,Histogram
0,['sTopics'],BrowsingHistory,0.487272,110870.0,0.000005,0.559884,"{'0': 0.09336289218929114, '1': 0.067365912040..."

In [27]:
# Prior Bayes vulnerability.
display(results['re_id']['Prior'][0], results['att_inf']['Prior'][0])

5.0499184438171325e-06

5.0499184438171325e-06

In [28]:
# Posterior Bayes vulnerability.
display(results['re_id']['Posterior'][0], results['att_inf']['Posterior'][0])

0.5598844578660055

0.5598844578660055

In [29]:
# Bayes leakage.
display(results['re_id']['Posterior'][0]/results['re_id']['Prior'][0], results['att_inf']['Posterior'][0]/results['att_inf']['Prior'][0])

110870.0

110870.0

### Unique sets

In [30]:
%%time
display(aol_experimental_google_generalization['sTopics'].map(lambda x : str(x)).nunique())

110870

CPU times: user 134 ms, sys: 3.65 ms, total: 138 ms
Wall time: 136 ms

## Experiments 8 and 9: Topics with Generalization and Bounded Noise on AOL experimental dataset with Google Taxonomy Classification v1; and Topics with Generalization, Bounded Noise, and Differential Privacy on AOL experimental dataset with Google Taxonomy Classification v1

In [31]:
display(aol_experimental_google_generalization)

,RandID,BrowsingHistory,AllTopics,sTopics
0,1,"[('kidshealth.org', Timestamp('2006-03-01 11:5...","[""'258'"", ""'276'"", ""'258'"", ""'276'"", ""'258'"", ...","[""'149'"", ""'234'"", ""'258'"", ""'276'"", ""'56'""]"
1,3,"[('google.com', Timestamp('2006-03-18 15:06:00...","[""'219'"", ""'239'"", ""'289'"", ""'258'"", ""'276'"", ...","[""'1'"", ""'180'"", ""'186'"", ""'258'"", ""'276'""]"
2,4,"[('foxnews.com', Timestamp('2006-03-12 20:33:2...","[""'1'"", ""'243'"", ""'219'""]","[""'1'"", ""'217'"", ""'219'"", ""'243'"", ""'306'""]"
3,5,"[('foxnews.com', Timestamp('2006-03-22 00:22:5...","[""'1'"", ""'243'"", ""'103'"", ""'1'"", ""'215'"", ""'24...","[""'1'"", ""'103'"", ""'215'"", ""'239'"", ""'243'""]"
4,6,"[('google.com', Timestamp('2006-03-06 15:07:17...","[""'219'"", ""'219'"", ""'219'"", ""'219'"", ""'219'"", ...","[""'12'"", ""'219'"", ""'289'"", ""'299'"", ""'314'""]"
...,...,...,...,...
198018,521683,"[('imdb.com', Timestamp('2006-04-08 17:05:00')...","[""'12'"", ""'45'"", ""'1'"", ""'243'""]","[""'1'"", ""'12'"", ""'230'"", ""'243'"", ""'45'""]"
198019,521686,"[('flickr.com', Timestamp('2006-03-12 21:19:11...","[""'42'"", ""'250'"", ""'253'"", ""'57'"", ""'62'"", ""'8...","[""'248'"", ""'250'"", ""'253'"", ""'62'"", ""'83'""]"
198020,521688,"[('aol.com', Timestamp('2006-03-16 16:59:47'))...","[""'1'"", ""'215'"", ""'243'"", ""'289'"", ""'275'""]","[""'1'"", ""'215'"", ""'243'"", ""'275'"", ""'289'""]"
198021,521689,"[('msn.com', Timestamp('2006-03-04 01:07:45'))...","[""'1'"", ""'215'"", ""'243'"", ""'219'"", ""'219'"", ""'...","[""'1'"", ""'215'"", ""'219'"", ""'243'"", ""'334'""]"
198022,521691,"[('ups.com', Timestamp('2006-03-07 21:29:17'))...","[""'103'"", ""'103'"", ""'103'"", ""'219'"", ""'219'""]","[""'103'"", ""'215'"", ""'219'"", ""'336'"", ""'81'""]"

In [32]:
%%time
# Computes the number of unique seen topics.
aol_experimental_google_seen_topics = sorted(list(set([x for y in aol_experimental_google_generalization['AllTopics'] for x in y.replace('[','').replace(']','').replace(' ','').replace('"','').split(',')])))
display(len(aol_experimental_google_seen_topics))

169

CPU times: user 860 ms, sys: 177 ms, total: 1.04 s
Wall time: 1.03 s

### Privacy

In [33]:
%%time
temp_top_S = {tup.Index : {t : 1 for t in tup.sTopics.replace('[','').replace(']','').replace(' ','').replace('\'','').replace('"','').split(',')} for tup in aol_experimental_google_generalization.itertuples()}

CPU times: user 831 ms, sys: 48.3 ms, total: 879 ms
Wall time: 876 ms

In [34]:
%%time
S = 5
M = len(aol_experimental_google_seen_topics)
R = 0.05
# Defines BN (bounded noise) channel for AOL-experimental-Google-Topics-Classification-v1 data.
aol_experimental_google_channel_bn = pandas.DataFrame.from_dict({k : [1/S if c in v else 0 for c in sorted([c.replace("'","") for c in aol_experimental_google_seen_topics])] for k,v in temp_top_S.items()}, orient='index', columns=sorted([c.replace("'","") for c in aol_experimental_google_seen_topics]))

CPU times: user 22 s, sys: 641 ms, total: 22.6 s
Wall time: 22.6 s

In [35]:
%%time
aol_experimental_google_all_topics = ["'" + str(i) + "'" for i in range(1,350)]
M = len(aol_experimental_google_all_topics)
# Defines DP (differential privacy) channel for AOL-experimental-Google-Topics-Classification-v1 data.
aol_experimental_google_channel_bn_dp = pandas.DataFrame.from_dict({k : [((1-R)/S) + (R/M) if c in v else (R/M) for c in sorted([c.replace("'","") for c in aol_experimental_google_all_topics])] for k,v in temp_top_S.items()}, orient='index', columns=sorted([c.replace("'","") for c in aol_experimental_google_all_topics]))

CPU times: user 45 s, sys: 2.01 s, total: 47 s
Wall time: 47 s

In [36]:
# Cummulative sums of channels rows for sanity check.
display(aol_experimental_google_channel_bn.cumsum(axis=1))
display(aol_experimental_google_channel_bn_dp.cumsum(axis=1))

,1,100,102,103,104,108,109,11,112,114,...,82,83,84,86,88,92,94,96,97,99
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,0.2,0.2,0.2,0.4,0.4,0.4,0.4,0.4,0.4,0.4,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198018,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
198019,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
198020,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
198021,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
198022,0.0,0.0,0.0,0.2,0.2,0.2,0.2,0.2,0.2,0.2,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

,1,10,100,101,102,103,104,105,106,107,...,90,91,92,93,94,95,96,97,98,99
0,0.000143,0.000287,0.00043,0.000573,0.000716,0.00086,0.001003,0.001146,0.001289,0.001433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
1,0.190143,0.190287,0.19043,0.190573,0.190716,0.19086,0.191003,0.191146,0.191289,0.191433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
2,0.190143,0.190287,0.19043,0.190573,0.190716,0.19086,0.191003,0.191146,0.191289,0.191433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
3,0.190143,0.190287,0.19043,0.190573,0.190716,0.38086,0.381003,0.381146,0.381289,0.381433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
4,0.000143,0.000287,0.00043,0.000573,0.000716,0.00086,0.001003,0.001146,0.001289,0.001433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198018,0.190143,0.190287,0.19043,0.190573,0.190716,0.19086,0.191003,0.191146,0.191289,0.191433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
198019,0.000143,0.000287,0.00043,0.000573,0.000716,0.00086,0.001003,0.001146,0.001289,0.001433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
198020,0.190143,0.190287,0.19043,0.190573,0.190716,0.19086,0.191003,0.191146,0.191289,0.191433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
198021,0.190143,0.190287,0.19043,0.190573,0.190716,0.19086,0.191003,0.191146,0.191289,0.191433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
198022,0.000143,0.000287,0.00043,0.000573,0.000716,0.19086,0.191003,0.191146,0.191289,0.191433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0

In [37]:
%%time
# Defines uniform prior probability distribution on individuals, i.e. RandIDs.
N = len(aol_experimental_google_channel_bn.index)
aol_experimental_google_bn_dp_prior = numpy.array([1/N for row in range(N)])

CPU times: user 22.4 ms, sys: 0 ns, total: 22.4 ms
Wall time: 22 ms

In [38]:
%%time
# Prior and Posterior Bayes vulnerabilities.
display("Prior: " + str(qif.measure.bayes_vuln.prior(aol_experimental_google_bn_dp_prior)))
display("BN Posterior: " + str(qif.measure.bayes_vuln.posterior(aol_experimental_google_bn_dp_prior, aol_experimental_google_channel_bn.to_numpy())))
display("DP Posterior: " + str(qif.measure.bayes_vuln.posterior(aol_experimental_google_bn_dp_prior, aol_experimental_google_channel_bn_dp.to_numpy())))

'Prior: 5.0499184438171325e-06'

'BN Posterior: 0.00017068724340101878'

'DP Posterior: 0.00016240537715315882'

CPU times: user 118 ms, sys: 118 Âµs, total: 118 ms
Wall time: 115 ms

In [39]:
%%time
# Bayes leakages.
display("BN Leakage: " + str(qif.measure.bayes_vuln.posterior(aol_experimental_google_bn_dp_prior, aol_experimental_google_channel_bn.to_numpy())/qif.measure.bayes_vuln.prior(aol_experimental_google_bn_dp_prior)))
display("DP Leakage: " + str(qif.measure.bayes_vuln.posterior(aol_experimental_google_bn_dp_prior, aol_experimental_google_channel_bn_dp.to_numpy())/qif.measure.bayes_vuln.prior(aol_experimental_google_bn_dp_prior)))

'BN Leakage: 33.79999999999994'

'DP Leakage: 32.15999999999997'

CPU times: user 110 ms, sys: 34 Âµs, total: 110 ms
Wall time: 108 ms

### Utility

In [40]:
%%time
# Defines (non-uniform) prior probability distribution on lists of sTopics.

# Defines list of lists of topics.
aol_experimental_google_top_S = [str(list(v.keys())).replace("\"","").replace("\'","") for k,v in temp_top_S.items()]

# Computes occurrences for each list of topics and total number of lists.
aol_experimental_google_top_S_counts = dict(Counter(aol_experimental_google_top_S))
total = sum(aol_experimental_google_top_S_counts.values())

# Defines the prior probability distribution as a DataFrame.
d = {case : aol_experimental_google_top_S_counts[case]/total for case in aol_experimental_google_top_S_counts}
aol_experimental_google_top_S_prior = pandas.DataFrame.from_dict(d, orient='index', columns=['prior'])
aol_experimental_google_top_S_prior.index.names = ['topics']

CPU times: user 396 ms, sys: 4.02 ms, total: 400 ms
Wall time: 397 ms

In [41]:
display(aol_experimental_google_top_S_prior)

                             prior
topics
[149, 234, 258, 276, 56]  0.000005
[1, 180, 186, 258, 276]   0.000005
[1, 217, 219, 243, 306]   0.000005
[1, 103, 215, 239, 243]   0.000086
[12, 219, 289, 299, 314]  0.000005
...                            ...
[198, 266, 275, 300, 99]  0.000005
[274, 289, 332, 344, 40]  0.000005
[1, 12, 230, 243, 45]     0.000005
[248, 250, 253, 62, 83]   0.000005
[103, 215, 219, 336, 81]  0.000005

[110870 rows x 1 columns]

In [42]:
%%time
S = 5
M = len(aol_experimental_google_seen_topics)
R = 0.05
# Defines BN (bounded noise) channel for AOL-experimental-Google-Topics-Classification-v1 data.
aol_experimental_google_channel_bn = pandas.DataFrame.from_dict({case : [1/S if c in case.replace('[','').replace(']','').split(', ') else 0 for c in sorted([c.replace("'","") for c in aol_experimental_google_seen_topics])] for case in sorted(d.keys())}, orient='index', columns=sorted([c.replace("'","") for c in aol_experimental_google_seen_topics]))

CPU times: user 22 s, sys: 60.2 ms, total: 22.1 s
Wall time: 22 s

In [43]:
%%time
M = len(aol_experimental_google_all_topics)
# Defines DP (differential privacy) channel for AOL-experimental-Google-Topics-Classification-v1 data.
aol_experimental_google_channel_bn_dp = pandas.DataFrame.from_dict({case : [((1-R)/S) + (R/M) if c in case.replace('[','').replace(']','').split(', ') else (R/M) for c in sorted([c.replace("'","") for c in aol_experimental_google_all_topics])] for case in sorted(d.keys())}, orient='index', columns=sorted([c.replace("'","") for c in aol_experimental_google_all_topics]))

CPU times: user 45.7 s, sys: 996 ms, total: 46.7 s
Wall time: 46.7 s

In [44]:
# Cummulative sums of channels rows for sanity check.
display(aol_experimental_google_channel_bn.cumsum(axis=1))
display(aol_experimental_google_channel_bn_dp.cumsum(axis=1))

,1,100,102,103,104,108,109,11,112,114,...,82,83,84,86,88,92,94,96,97,99
"[1, 100, 102, 215, 243]",0.2,0.4,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
"[1, 100, 103, 104, 57]",0.2,0.4,0.4,0.6,0.8,0.8,0.8,0.8,0.8,0.8,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
"[1, 100, 103, 12, 243]",0.2,0.4,0.4,0.6,0.6,0.6,0.6,0.6,0.6,0.6,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
"[1, 100, 103, 126, 243]",0.2,0.4,0.4,0.6,0.6,0.6,0.6,0.6,0.6,0.6,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
"[1, 100, 103, 126, 249]",0.2,0.4,0.4,0.6,0.6,0.6,0.6,0.6,0.6,0.6,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"[48, 57, 62, 82, 83]",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
"[57, 62, 70, 81, 83]",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
"[57, 62, 81, 82, 83]",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
"[57, 62, 83, 88, 92]",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4,0.6,0.6,0.6,0.8,1.0,1.0,1.0,1.0,1.0
"[57, 62, 83, 92, 94]",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4,0.6,0.6,0.6,0.6,0.8,1.0,1.0,1.0,1.0

,1,10,100,101,102,103,104,105,106,107,...,90,91,92,93,94,95,96,97,98,99
"[1, 100, 102, 215, 243]",0.190143,0.190287,0.38043,0.380573,0.570716,0.57086,0.571003,0.571146,0.571289,0.571433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
"[1, 100, 103, 104, 57]",0.190143,0.190287,0.38043,0.380573,0.380716,0.57086,0.761003,0.761146,0.761289,0.761433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
"[1, 100, 103, 12, 243]",0.190143,0.190287,0.38043,0.380573,0.380716,0.57086,0.571003,0.571146,0.571289,0.571433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
"[1, 100, 103, 126, 243]",0.190143,0.190287,0.38043,0.380573,0.380716,0.57086,0.571003,0.571146,0.571289,0.571433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
"[1, 100, 103, 126, 249]",0.190143,0.190287,0.38043,0.380573,0.380716,0.57086,0.571003,0.571146,0.571289,0.571433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"[48, 57, 62, 82, 83]",0.000143,0.000287,0.00043,0.000573,0.000716,0.00086,0.001003,0.001146,0.001289,0.001433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
"[57, 62, 70, 81, 83]",0.000143,0.000287,0.00043,0.000573,0.000716,0.00086,0.001003,0.001146,0.001289,0.001433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
"[57, 62, 81, 82, 83]",0.000143,0.000287,0.00043,0.000573,0.000716,0.00086,0.001003,0.001146,0.001289,0.001433,...,0.998711,0.998854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
"[57, 62, 83, 88, 92]",0.000143,0.000287,0.00043,0.000573,0.000716,0.00086,0.001003,0.001146,0.001289,0.001433,...,0.808711,0.808854,0.998997,0.99914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0
"[57, 62, 83, 92, 94]",0.000143,0.000287,0.00043,0.000573,0.000716,0.00086,0.001003,0.001146,0.001289,0.001433,...,0.618711,0.618854,0.808997,0.80914,0.999284,0.999427,0.99957,0.999713,0.999857,1.0

In [45]:
%%time
# Prior and Posterior Bayes vulnerabilities.
display("Prior: " + str(qif.measure.bayes_vuln.prior(aol_experimental_google_top_S_prior['prior'].to_numpy())))
display("BN Posterior: " + str(qif.measure.bayes_vuln.posterior(aol_experimental_google_top_S_prior['prior'].to_numpy(), aol_experimental_google_channel_bn.to_numpy())))
display("DP Posterior: " + str(qif.measure.bayes_vuln.posterior(aol_experimental_google_top_S_prior['prior'].to_numpy(), aol_experimental_google_channel_bn_dp.to_numpy())))

'Prior: 0.014892209490816724'

'BN Posterior: 0.047507612752054056'

'DP Posterior: 0.045550303141973975'

CPU times: user 185 ms, sys: 72.1 ms, total: 257 ms
Wall time: 251 ms

In [46]:
%%time
# Bayes leakages.
display("BN Leakage: " + str(qif.measure.bayes_vuln.posterior(aol_experimental_google_top_S_prior['prior'].to_numpy(), aol_experimental_google_channel_bn.to_numpy())/qif.measure.bayes_vuln.prior(aol_experimental_google_top_S_prior['prior'].to_numpy())))
display("DP Leakage: " + str(qif.measure.bayes_vuln.posterior(aol_experimental_google_top_S_prior['prior'].to_numpy(), aol_experimental_google_channel_bn_dp.to_numpy())/qif.measure.bayes_vuln.prior(aol_experimental_google_top_S_prior['prior'].to_numpy())))

'BN Leakage: 3.190098338419803'

'DP Leakage: 3.058666557844392'

CPU times: user 179 ms, sys: 80.1 ms, total: 259 ms
Wall time: 253 ms

#### Bayes over uniform prior

In [47]:
N = len(aol_experimental_google_channel_bn.index)

In [48]:
%%time
display("BN Leakage: " + str(qif.measure.bayes_vuln.posterior(numpy.array([1/N for row in range(N)]), aol_experimental_google_channel_bn.to_numpy())/qif.measure.bayes_vuln.prior(numpy.array([1/N for row in range(N)]))))
display("DP Leakage: " + str(qif.measure.bayes_vuln.posterior(numpy.array([1/N for row in range(N)]), aol_experimental_google_channel_bn_dp.to_numpy())/qif.measure.bayes_vuln.prior(numpy.array([1/N for row in range(N)]))))

'BN Leakage: 33.79999999999994'

'DP Leakage: 32.15999999999997'

CPU times: user 119 ms, sys: 148 Âµs, total: 119 ms
Wall time: 117 ms

#### IBA gain

In [49]:
%%time
# Defines IBA gain function matrix for BN (bounded noise) channel for AOL-experimental-Google-Topics-Classification-v1 data.
G_IBA_bn = pandas.DataFrame.from_dict({case : [1 if c in case.replace('[','').replace(']','').split(', ') else 0 for c in sorted([c.replace("'","") for c in aol_experimental_google_seen_topics])] for case in sorted(d.keys())}, orient='index', columns=sorted([c.replace("'","") for c in aol_experimental_google_seen_topics]))
display(G_IBA_bn.T)

,"[1, 100, 102, 215, 243]","[1, 100, 103, 104, 57]","[1, 100, 103, 12, 243]","[1, 100, 103, 126, 243]","[1, 100, 103, 126, 249]","[1, 100, 103, 126, 289]","[1, 100, 103, 129, 243]","[1, 100, 103, 140, 289]","[1, 100, 103, 149, 243]","[1, 100, 103, 149, 263]",...,"[4, 57, 62, 83, 86]","[40, 57, 62, 83, 99]","[43, 57, 62, 81, 83]","[43, 58, 7, 70, 83]","[45, 57, 62, 81, 83]","[48, 57, 62, 82, 83]","[57, 62, 70, 81, 83]","[57, 62, 81, 82, 83]","[57, 62, 83, 88, 92]","[57, 62, 83, 92, 94]"
1,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
100,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
102,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
103,0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
104,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
94,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

CPU times: user 22.1 s, sys: 7.85 ms, total: 22.1 s
Wall time: 22.1 s

In [50]:
%%time
# Defines IBA gain function matrix for DP (differential privacy) channel for AOL-experimental-Google-Topics-Classification-v1 data.
G_IBA_bn_dp = pandas.DataFrame.from_dict({case : [1 if c in case.replace('[','').replace(']','').split(', ') else 0 for c in sorted([c.replace("'","") for c in aol_experimental_google_all_topics])] for case in sorted(d.keys())}, orient='index', columns=sorted([c.replace("'","") for c in aol_experimental_google_all_topics]))
display(G_IBA_bn_dp.T)

,"[1, 100, 102, 215, 243]","[1, 100, 103, 104, 57]","[1, 100, 103, 12, 243]","[1, 100, 103, 126, 243]","[1, 100, 103, 126, 249]","[1, 100, 103, 126, 289]","[1, 100, 103, 129, 243]","[1, 100, 103, 140, 289]","[1, 100, 103, 149, 243]","[1, 100, 103, 149, 263]",...,"[4, 57, 62, 83, 86]","[40, 57, 62, 83, 99]","[43, 57, 62, 81, 83]","[43, 58, 7, 70, 83]","[45, 57, 62, 81, 83]","[48, 57, 62, 82, 83]","[57, 62, 70, 81, 83]","[57, 62, 81, 82, 83]","[57, 62, 83, 88, 92]","[57, 62, 83, 92, 94]"
1,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
101,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

CPU times: user 46.3 s, sys: 300 ms, total: 46.6 s
Wall time: 46.6 s

In [51]:
%%time
# Prior and Posterior IBA gains for BN (bounded noise) channel.
display("BN Prior: " + str(qif.measure.g_vuln.prior(G_IBA_bn.T.to_numpy(dtype=numpy.int32), aol_experimental_google_top_S_prior['prior'].to_numpy())))
display("BN Posterior: " + str(qif.measure.g_vuln.posterior(G_IBA_bn.T.to_numpy(dtype=numpy.int32), aol_experimental_google_top_S_prior['prior'].to_numpy(), aol_experimental_google_channel_bn.to_numpy())))

'BN Prior: 0.4210823995191495'

'BN Posterior: 1.0000000000000002'

CPU times: user 1.24 s, sys: 712 ms, total: 1.96 s
Wall time: 463 ms

In [52]:
%%time
# IBA leakage for BN (bounded noise) channel.
display("BN Leakage: " + str(qif.measure.g_vuln.posterior(G_IBA_bn.T.to_numpy(dtype=numpy.int32), aol_experimental_google_top_S_prior['prior'].to_numpy(), aol_experimental_google_channel_bn.to_numpy())/qif.measure.g_vuln.prior(G_IBA_bn.T.to_numpy(dtype=numpy.int32), aol_experimental_google_top_S_prior['prior'].to_numpy())))

'BN Leakage: 2.3748321020824887'

CPU times: user 1.34 s, sys: 1.45 s, total: 2.79 s
Wall time: 502 ms

In [53]:
%%time
# Prior and Posterior IBA gains for DP (differential privacy) channel.
display("DP Prior: " + str(qif.measure.g_vuln.prior(G_IBA_bn_dp.T.to_numpy(dtype=numpy.int32), aol_experimental_google_top_S_prior['prior'].to_numpy())))
display("DP Posterior: " + str(qif.measure.g_vuln.posterior(G_IBA_bn_dp.T.to_numpy(dtype=numpy.int32), aol_experimental_google_top_S_prior['prior'].to_numpy(), aol_experimental_google_channel_bn_dp.to_numpy())))

'DP Prior: 0.4210823995191495'

'DP Posterior: 0.9615751908185466'

CPU times: user 3.65 s, sys: 2 s, total: 5.65 s
Wall time: 1.23 s

In [54]:
%%time
# IBA leakage for DP (differential privacy) channel.
display("DP Leakage: " + str(qif.measure.g_vuln.posterior(G_IBA_bn_dp.T.to_numpy(dtype=numpy.int32), aol_experimental_google_top_S_prior['prior'].to_numpy(), aol_experimental_google_channel_bn_dp.to_numpy())/qif.measure.g_vuln.prior(G_IBA_bn_dp.T.to_numpy(dtype=numpy.int32), aol_experimental_google_top_S_prior['prior'].to_numpy())))

'DP Leakage: 2.2835796317219788'

CPU times: user 3.28 s, sys: 2.05 s, total: 5.33 s
Wall time: 1.15 s